import type { Metadata } from "next";

import localFont from "next/font/local";
import { Poppins } from "next/font/google";

import Footer from "@/components/Footer";

import "./globals.css";
import MobileFooter from "@/components/Footer/MobileFooter";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

const digital_geometric = localFont({
  src: [
    {
      path: "../../public/fonts/digital geometric/digital geometric bold.ttf",
      weight: "700",
      style: "normal",
    },
    
  ],
  variable: "--font-digital_geometric",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${digital_geometric.variable} antialiased`}
      >
        {children}
        <Footer/>
        <MobileFooter/>
      </body>
    </html>
  );
}
